### ISSUE TITLE
Upcoming dates and milestones for IPPD

### ISSUE THREAD

**Issue by jvallera** [jvallera/IPPD-Webmaker-Institute#1]
- [ ] Follow up call one: March 7, 2016, 6-7 pm 
- [ ] Follow up call 2: April 4, 2016, 6-7 pm pm EDT
- [ ] February 29/Prompt 1: What are you most interested in/excited about working on in the coming weeks?
- [ ] March 14/Prompt 2: What project(s) did you choose to work on and how do you plan to implement it?
- [ ] March 21/Prompt 3: What challenges have arisen so far? Do you have any adaptations or suggestions based on experiences?
- [ ] March 28/Prompt 4: What are your plans for testing your project?
- [ ] April 11/Prompt 5: How do you plan to share your work in the open?
